gatewayClass:
  create: false
  name: aws-alb-gateway-class
  controllerName: gateway.k8s.aws/alb

gateway:
  create: true
  name: cluster-gateway
  namespace: gateway
  hostname: "*.tunebridge.online"
  tlsSecretName: ""

lbConfiguration:
  name: test-gw-lbconfig-1
  defaultCertificate: "" # patch later with ACM cert ARN from terraform output

argocdRoute:
  enabled: true
  namespace: argocd
  hostname: "argocd.tunebridge.online"
  sectionName: https
  serviceName: argocd-server
  servicePort: 80
