{{- if .Values.secretStore.enabled }}
{{- with .Values.secretStore }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      role: {{ .provider.aws.role }}
{{- end }}
{{- end }}
