{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecom-app.fullname" . }}
  labels:
    {{- include "ecom-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env.prod: {{ required "secret.envProd is required when secret.create is true" .Values.secret.envProd | quote }}
  .env.keys: {{ required "secret.dotenvxPrivateKey is required when secret.create is true" .Values.secret.dotenvxPrivateKey | quote }}
{{- end }}
