{{- range $configName, $config := .Values.targetGroupConfiguration }}
{{- if $config.enabled }}
---
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: {{ required (printf "targetGroupConfiguration.%s.name is required when enabled is true" $configName) $config.name }}
  namespace: {{ required (printf "targetGroupConfiguration.%s.namespace is required when enabled is true" $configName) $config.namespace }}
  labels:
    {{- include "gateway-platform.labels" $ | nindent 4 }}
spec:
  targetReference:
    name: {{ required (printf "targetGroupConfiguration.%s.targetReference.name is required when enabled is true" $configName) $config.targetReference.name }}
    {{- with $config.targetReference.group }}
    group: {{ . | quote }}
    {{- end }}
    {{- with $config.targetReference.kind }}
    kind: {{ . | quote }}
    {{- end }}
  defaultConfiguration:
    {{- toYaml (required (printf "targetGroupConfiguration.%s.defaultConfiguration is required when enabled is true" $configName) $config.defaultConfiguration) | nindent 4 }}
{{- end }}
{{- end }}
