apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-deployment
spec:
  selector:
    matchLabels:
      app: my-ecom-app
  template:
    metadata:
      labels:
        app: my-ecom-app
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: ecom-app-secret
      containers:
        - name: ecom-container
          image: tuannamnguyen290602/ecom-web:v6
          args: ["dotenvx", "run", "-f", "/etc/secret-volume/.env.prod", "--", "php", "-S", "0.0.0.0:8000", "-t", "/var/www/html"]
          env:
            - name: HERO_HEADING
              valueFrom:
                configMapKeyRef:
                  key: hero_heading
                  name: my-ecom-app-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 3
            timeoutSeconds: 3
            httpGet:
              path: /healthz
              port: 8000
          ports:
            - containerPort: 8000
