apiVersion: v1
kind: Secret
metadata:
  name: ecom-app-secret
type: Opaque
data:
  .env.prod: |
    Iy8tLS0tLS0tLS0tLS0tLS0tLS0tW0RPVEVOVl9QVUJMSUNfS0VZXS0tLS0tLS0tLS0tLS0tLS0t
    LS0tLwojLyAgICAgICAgICAgIHB1YmxpYy1rZXkgZW5jcnlwdGlvbiBmb3IgLmVudiBmaWxlcyAg
    ICAgICAgICAvCiMvICAgICAgIFtob3cgaXQgd29ya3NdKGh0dHBzOi8vZG90ZW52eC5jb20vZW5j
    cnlwdGlvbikgICAgIC8KIy8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
    LS0tLS0tLS0tLS0tLS0tLS0tLwpET1RFTlZfUFVCTElDX0tFWV9QUk9EPSIwMjk0OTYzZjczZTVl
    NzcyYzczMDkyMmM0ODJiOWU0NzNlOThlZGRjYTBjYzc4MzdjYTZlNTdiMjY5NWU2MGE4NTQiCgoj
    IC5lbnYucHJvZApEQl9IT1NUPWVuY3J5cHRlZDpCRTIzNi9qdEhuL0loOHI2N1pBU1RJQUtSYm5L
    VWV1bjBoc29kNTl5M3AxcnZ1eVVONkMxY3hFazNoN2grdmJyZ0ZVSkQ1UFhZS3EwK1VoMFd2ZXVF
    bnhqMVRqdC85Y3ltaTRIenhYSiszcGUzaTZKNjJVTEhBK2liL0FTcEdJaWU0RHZHWVR5RklIbkdB
    PT0KREJfVVNFUj1lbmNyeXB0ZWQ6QkdKMFFaZ2lXYXl6ZUpqY0t3RWJZakJ4QWMxNnpvQWdNR244
    QW5HWDVQTFUrcEM0bk9qdUxvaXo1ODV1bHlqdTBLSkFrdG5YTzJDbnF3VjJYcXlmZCtYeVB2SGFD
    cGFNYWFlNVIyK2FjdUg0QVYwOUIwQ2IxSmVVTkpDbEd1cEtUWXcwdUNPWFUvNjgKREJfUEFTU1dP
    UkQ9ZW5jcnlwdGVkOkJNRkF1SitNZm4vUmpkV3kvZUF0NW1sZjU4NHFVc2pzMjVFTmgvMVZPRklw
    SmlNd0dWdGdzRjR5c3FxclpQY1JxbFkyS2Nka2ZtRXBnanNzay9kbFVWRFA1Zyt0YStlOUR6eDVE
    Z0xob0Q3dlN2NGZRTkVWd3V0WmRFNzZyRVoyRWdXQllVaGI3eDNFdGNYUGhnPT0KREJfTkFNRT1l
    bmNyeXB0ZWQ6QkZFajlFTk9BMDBvbG54K0g1WThXZ2p1ZXpvRHVTc2JxZlF6UUpWeXFHN1hQY2t0
    ZHFrTk8wR252aGpLWjdKcTYwTU02Zm1INzlYNUlPTG1zSEt0Wk9McXE0eTZHOWZJL0V6UWI4NlRN
    ZzBmbEE2VjJhNGdiRTAyeTlEbytjblNsZjE3VlpFdUdRPT0K
